language: python
branches:
  only:
    - desarrollo

sudo: required

services:
- docker

env:
  DOCKER_COMPOSE_VERSION: 1.24.0

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/{$DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - /usr/local/bin/docker-compose up -d

script:
  - /usr/local/bin/docker-compose run --rm alumnos pytest

cache:
  - pip