version: '2.3'
services:
  alumnos_backend:
    container_name: seguimiento-academico
    restart: always
    build: .
    command: gunicorn -w 1 -b :8001 --pythonpath alumnos --env DJANGO_SETTINGS_MODULE=alumnos.settings alumnos.wsgi:application
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  nginx:
    container_name: nginx-container
    restart: always
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - alumnos_backend
volumes:
  postgres_data: